# Colors
set $rosewater #f4dbd6
set $flamingo #f0c6c6
set $pink #f5bde6
set $mauve #c6a0f6
set $red #ed8796
set $maroon #ee99a0
set $peach #f5a97f
set $yellow #eed49f
set $green #a6da95
set $teal #8bd5ca
set $sky #91d7e3
set $sapphire #7dc4e4
set $blue #8aadf4
set $lavender #b7bdf8
set $text #cad3f5
set $subtext1 #b8c0e0
set $subtext0 #a5adcb
set $overlay2 #939ab7
set $overlay1 #8087a2
set $overlay0 #6e738d
set $surface2 #5b6078
set $surface1 #494d64
set $surface0 #363a4f
set $base #24273a
set $mantle #1e2030
set $crust #181926

# Target                 title     bg    text      indicator    border
client.focused           $lavender $base $text  $rosewater $lavender
client.focused_inactive  $overlay0 $base $text  $rosewater $overlay0
client.unfocused         $overlay0 $base $text  $rosewater $overlay0
client.urgent            $peach    $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base

# Window title icon
for_window [all] title_window_icon on
for_window [all] title_window_icon padding 5px
title_align left

# Gaps
gaps inner 10
gaps outer 1

# window border
for_window [class="^.*"] border pixel 2
for_window [class="Eog"] floating enable
for_window [class="qalculate-gtk"] floating enable

# Bar
bar {
    position top
    status_command i3status
	position top
	workspace_min_width 24
	padding 5px 10px 5px 10px
	strip_workspace_numbers yes

    tray_padding 5
    separator_symbol " | "
    workspace_buttons yes
    colors {
        background         $base
        statusline         $text
        focused_statusline $text
        focused_separator  $pink
        focused_workspace  $base $base $green
        active_workspace   $base $base $blue
        inactive_workspace $base $base $surface1
        urgent_workspace   $base $base $surface1
        binding_mode       $base $base $surface1
    }
}

# Display Wallpaper
exec_always feh --bg-fill ~/Documents/Repos/.dotfiles/walls/010.png

